### ISSUE TITLE
Duplicate cross project dependencies should be handled gracefully

### ISSUE THREAD

**Issue by kushsharma** [odpf/optimus#137]
If a job inferred a cross-project dependency from its task and the same dependency is also mentioned in `job.yaml` specification, they are treated as duplicates. The reason is inferred dependencies when used in map for dependencies uses job name whereas cross-project dependency mentioned in specification uses `project_name/job_name` so duplicates are created inside the same dependency map.
For example:
```yaml
...
dependencies:
- job: foo-project/bar-job
  type: inter
```
The [map](https://github.com/odpf/optimus/blob/0a8d332ea1d989ce7e2fddc0ee4b80be577d3c5b/job/dependency_resolver.go#L165) will have two jobs as `bar-job` and `foo-project/bar-job`.

Although users can choose to simply write the spec properly, the expected result is Optimus to handle it gracefully.

**Comment by sravankorumilli** [comment]
so the optimus compiles it as two sensors right?

**Comment by kushsharma** [comment]
No, actually it generates two of such dependencies
```
d1 >> t1
d1 >> t1
```
but airflow complains of having duplicate order of tasks and simply fails to read the dag.

**Comment by sravankorumilli** [comment]
won't be just addressing this issue alone, lets address entire entire dependency resolution issues as part of https://github.com/odpf/optimus/issues/176
