### ISSUE TITLE
Print Basic Details of Image Version & Optimus Client & Server Versions

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#139]
In order to support better debuggability, at the time of running of plugins.
1. Would be good to print image version. 
2. Optimus client & optimus server versions

**Comment by kushsharma** [comment]
1. Docker image version is normally part of airflow dag files, do we want them to be printed during the execution of the image as well? 
2. At the top of the file, you will also find what version was used of optimus server to compile that dag. The client version is known to plugins as they are baked inside the docker image although we don't print them.

Wanted to know the reasoning why do we need these printed again and what kind of situations are we debugging?

**Comment by sravankorumilli** [comment]
What we see in the dags is the latest image version, so if there is an issue then we need to understand what is the version at the time of running.

**Comment by kushsharma** [comment]
Make sense I think because we override KubePodOperator, maybe we log the image in logs using that in `__lib.py` file? We don't have to do it for all the images seperately.
