### ISSUE TITLE
Optimus command to start a program with context envs injected by default

### ISSUE THREAD

**Issue by kushsharma** [odpf/optimus#14]
When a plugin docker container executes and requires configuration/asset files as input, it can either use GRPC/REST calls to fetch them from optimus or there is an existing command `optimus admin build instance` that prints them in the local filesystem.

What if we have a run command instead that will inject these configuration variables as env by default? Something like `optimus admin run instance python3 main.py --some-arg` where `python3 main.py --some-arg` will vary based on each plugin.

**Comment by sravankorumilli** [comment]
We donot need this as this will be addressed #362
