### ISSUE TITLE
Remove Success bool field from proto response

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#163]

**Comment by sbchaos** [comment]
In the current optimus protobuf files we have boolean fields to indicate the success, but in case of error we return a grpc error and field is always true in case of success. So we can remove all the boolean fields to indicate success and check for error.

**Comment by deryrahman** [comment]
@sbchaos should we also remove `ack` field? As what I understand here, `ack` means acknowledge when the client successfully receive an uncorrupted message from server. If the purpose is for that, we can safely remove it, I believe `.Recv()` guarantee that the message is complete

**Comment by deryrahman** [comment]
Find a case then success is `false` [here](https://github.com/odpf/optimus/blob/bfec87416a711c705f074a1938722fc7ef7f2b49/api/handler/v1beta1/observer.go#L32) and [here](https://github.com/odpf/optimus/blob/bfec87416a711c705f074a1938722fc7ef7f2b49/api/handler/v1beta1/observer.go#L76), in case of 1 job upload or resource update are failing, it will notify to client that deployment is fail ([here](https://github.com/odpf/optimus/blob/bfec87416a711c705f074a1938722fc7ef7f2b49/cmd/deploy.go#L243) and [here](https://github.com/odpf/optimus/blob/bfec87416a711c705f074a1938722fc7ef7f2b49/cmd/deploy.go#L175)) by marking field success as `false`.

I think, `success` field in proto response has different meaning with `error` returned by the function. `error` that returned by the function indicate there's a problem in grpc network level, and `success` field in response indicate the success / no success status that we can defined in the code level (for example like job & resource deployment as I mentioned above, message is successfully received by client stated as `error=nil`, but client will know if job upload or resource update is failed or not by looking into `success` field in response). cmiiw

**Comment by sbchaos** [comment]
@deryrahman In this case we are using grpc stream and we need to send the success/failure in the stream response so it makes sense to have success field (do we need ACK also ?).

The refactoring we need to do is mostly for the grpc Unary calls, where we should return an error in case of problem and not success as false.

**Comment by deryrahman** [comment]
@sbchaos  got it, make sense, we can remove `Success` field only for unary calls

**Comment by sravankorumilli** [comment]
addressed as part of this https://github.com/odpf/optimus/issues/430
