### ISSUE TITLE
Remove interface for Config provider and use the Config struct

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#164]

**Comment by deryrahman** [comment]
@sravankorumilli we have `conf.Admin` [here](https://github.com/odpf/optimus/blob/a8da326317c77a1040b653710b1bec09652859ff/config/config.go#L24) but not used. Can we safely remove this?

**Comment by kushsharma** [comment]
@deryrahman yeah we can remove this, its no longer needed

**Comment by sbchaos** [comment]
This is resolved.
