### ISSUE TITLE
Convert handler/adapter from interface to functions

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#165]

**Comment by sbchaos** [comment]
The current adapters convert from one struct to another and are not adapters for behaviour.
We need to convert all such adapter from using an interface to individual function. Function can be used to convert from one model to other.

**Comment by sbchaos** [comment]
Done for `api/handler/v1beta1/adapter.go`
Need to do for `store/postgres/adapter.go`

**Comment by ravisuhag** [comment]
@sbchaos Can you please link the corresponding PR with the issue?
