### ISSUE TITLE
Create separate servers from runtimeServer for backup, replay etc

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#166]
This will include creating smaller servers for the specific part and using them on the same grpc server to handle the specific functionality. For example

srv := grpc.NewServer()
rpx.RegisterReplayServer(srv, replaySvc)
rpx.RegisterBackupServer(srv, backupSvc)

**Comment by kushsharma** [comment]
You mean splitting up the proto definition or actual server on different ports?
