### ISSUE TITLE
CLI & API should Support Deployment of Single/Multiple Namespaces

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#184]
As per [RFC](https://github.com/odpf/optimus/pull/152) current deploy request accepts only for a single namespace, in a single api call we need to support deployment of single/multiple/all namespaces instead of limiting to single namespace.

**Out of Scope**

1. Integrating with the new flow.

**Comment by irainia** [comment]
@arinda-arif , it's possible mbak. so our plan so far is:
* get the namespace information:
  * if namespace is is one, then only one
  * if namespace is multiple, then multiple
  * if namespace is not specified, then all

however, the above behaviour only applies for some commands, such as deployment command, but not for others, such as create command. cc: @deryrahman
