### ISSUE TITLE
Optimus provide a mechanism to register a project & namespace through cli

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#204]
Currently, project & namespace cannot be register through Optimus CLI, as most of the users are CLI users, it would be better if there is a mechanism to register project & namespace.

Acceptance Criteria
1. User should be able to register a project without any namespace.
2. User should be able to register a namespace only.
3. User should be able to register both project & namespace together.
4. On deploy if any new project/namespace is modified it should be register/updated.
5. remove existing config init command

User experience
1. optimus project/namespace register

**Comment by deryrahman** [comment]
So far, the commands we've designed are something like this:

```
$ optimus project create
$ optimus namespace create

$ optimus project register // .optimus.yaml is exist -> create/update request to server
$ optimus project list --server
$ optimus namespace register --name="ns1"
$ optimus namespace list --server(opt) // list all namespace in project folder / server?
```

By definition:
```sh
$ optimus project create
# - create config `.optimus.yaml` in a root project directory
# - using interactive command, prompt

$ optimus namespace create
# - can only be run when project config is exist
# - define namespace folder
# - create config `.optimus.yaml` in that folder
# - using interactive command, prompt

$ optimus project register
# - create/update project to server

$ optimus project describe
# - describe project in current dir

$ optimus namespace register --name="ns1"
# - create/update namespace to server

$ optimus namespace list --server(opt)
# - list all namespace in project folder / server
```

cc: @irainia

**Comment by irainia** [comment]
update based on discussion:
* use `init` instead of `create` for `optimus project`
* add `describe` for `optimus namespace` just like in the project
* expect to have command be run outside of the root repo (project) dir like `--dir`
* deprecate `optimus config init`
* use only one `.optimus.yaml` file, which also includes both the project and namespace information

final commands will be:
```zsh
$ optimus project init --dir="dir"
# - create config `.optimus.yaml` in a root project directory
# - using interactive command, prompt

$ optimus namespace init --dir="dir"
# - can only be run when project config exists
# - define namespace folder
# - create config `.namespce.yaml` in that folder
# - using interactive command, prompt

$ optimus project register --dir="dir" --with-namespaces(opt)
# - create/update project to server with/without all namespaces

$ optimus project describe --dir="dir" --server(opt)
# - describe project in current dir / server

$ optimus namespace register --dir="dir" --name="ns1"
# - create/update namespace to server

$ optimus namespace describe "ns1" --dir="dir" --server(opt)
# - get detail of a specific namespace config in project folder / server

$ optimus namespace list --dir="dir" --server(opt)
# - list all namespace in project folder / server (without any detail) includes information whether a namespace is registered or not in the server
```

cc: @sravankorumilli

**Comment by sravankorumilli** [comment]
@irainia @deryrahman few more thoughts?

```
optimus init
optimus project register --dir="project_root_dir" --with-namespaces
optimus namespace register --dir="project_root_dir" --name="namespace_name"
optimus project describe --server=  --name=
optimus namespace describe --server=  --name=
optimus namespace list ---server= --name=
```

What Init should do?
Initialize a project such that the basic folder strucutre with the configured `.optimus.yaml` is set for the user to add specs and communicate to the server.

- Ask few basic questions which are needed like `project_name`, `optimus_server`, `scheduler`:`airflow` if `airflow` then `airflow_webserver_host`, `airflow_dags_storage_path`
- Ask another question around if user wants to initialize default namespace/workspace if yes then the location and datastores that you will be working with.
- `scheduler` is a new config which aiming at it is the user responsibility to define what scheduler is being used. So, we will move away from server defining the scheduler. 

IMO below mentioned details should be considered in the scope of this card.
1. initialization, registration and splitting of different structs for client & server.

**Comment by irainia** [comment]
> 

we can go with this route

**Comment by ravisuhag** [comment]
@sravankorumilli I think defining schedular should not be the responsibility of the end-user but only the admin. So I would recommend keeping this config on the server-side only. WDYT?

**Comment by kushsharma** [comment]
What if when user creates a project, it automatically creates a `default` namespace? Not everyone wants to namespace their specs from the start I guess? We can make it less complicated for simple users?

**Comment by kushsharma** [comment]
I agree with @ravisuhag on scheduler, currently our server can run with only one scheduler at a time. It doesn't help users to ask for `scheduler` when server can only support one.

**Comment by sravankorumilli** [comment]
@kushsharma even though it is a small convenience to the users, it just simplifies stuff for us at the moment. It is just asking a namespace config in extra. So, would suggest keep a namespace configured for all the jobs & resources we are adding.

**Comment by sravankorumilli** [comment]
@ravisuhag @kushsharma on scheduler, currently yes we support a single scheduler, but from the design choice that optimus supports multiple schedulers and with multi-tenancy, there is always a requirement for multiple tenants come up with their own schedulers.  this can be in our backlog, but no need to prioritize that.

**Comment by kushsharma** [comment]
> @ravisuhag @kushsharma on scheduler, currently yes we support a single scheduler, but from the design choice that optimus supports multiple schedulers and with multi-tenancy, there is always a requirement for multiple tenants come up with their own schedulers.  this can be in our backlog, but no need to prioritize that.

Okay, then as we think in near future we will not prioritize supporting multiple batch schedulers for multiple projects, I guess until we do that, let's keep the scheduler config same?

**Comment by kushsharma** [comment]
> @kushsharma even though it is a small convenience to the users, it just simplifies stuff for us at the moment. It is just asking a namespace config in extra. So, would suggest keep a namespace configured for all the jobs & resources we are adding.

Okay no big deal but it's just I have seen other tools also do this thing for example kubernetes. I believe we should prioritize user convenience over ours. 😅

**Comment by sravankorumilli** [comment]
sure @kushsharma, we can consider deploying to `default` namespace. But I believe when we start supporting `default` namespace then the ideal behaviour is when users doesn't specify any namespace during job or resource creation, operations happen on `default` namespace.
