### ISSUE TITLE
lib.py to be copiled along with the job deployment as that might result into inconsistent behaviour otherwise.

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#222]
There is no need of bootstrap, just copying while deploying is sufficient.

**Comment by sravankorumilli** [comment]
@sbchaos do we need to have bucket creation inside optimus, I believe we should expect bucket to be pre created

**Comment by sbchaos** [comment]
We are adding `__lib.py` file to the bucket at the time of startup. We can check existence of this file and write at the time of deploy.

**Comment by kushsharma** [comment]
I don't understand the reasoning? Did we just choose to remove the automation in favour of manual work?

**Comment by kushsharma** [comment]
When does it goes out of sync? Also isn't we used to create bucket if it was not present or local folder if the directory was not present?

**Comment by sravankorumilli** [comment]
Example and what we observed, there are changes in the lib.py which are not compatible with the dags, on new deployment the lib.py will get copied and all dags can't be loaded. It needs a redeployment of dags to be in sync with lib.py file.

**Comment by sravankorumilli** [comment]
Currently too, optimus doesn't create the buckets, on local setup it does. But if we need to we can do that during the deployment. But it is better to not do the bucket creation as, that means giving extra privileges to optimus which isn't good.
