### ISSUE TITLE
Executor should depend only on the secrets through JobSpec

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#224]
As part of this, let's avoid depending on secrets which are precreated outside in the kubernetes and let's just rely on the secrets provided in the optimus server.

**Acceptance Criteria :**
All officially supported plugins, should be changed to use these new secrets.

**Comment by sbchaos** [comment]
We have kept existing mechanism of secrets for backward compatibility, if the secrets are provided through job spec, they will be consumed in the plugin executor.
