### ISSUE TITLE
Optimus Commands functions are all package scoped, it is better to group them under specific group command structs

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#264]
The current `cmd` package contains many implementations in the scope of accepting the user input on how to execute Optimus. There are some issues being observed for the current approach:

* many functionalities are defined within one package, making the package itself seems bigger with a lot of functions, variables, and constants that are accessible accross the package
* with many components defined within one package, some of it could conflict with one another, and there were cases during development that two components (in this example, variables) were defined but served the same purpose
* during development, IDE or text editor's suggestion could clutter with other functionalities

To address the mentioned issues above, one approach that can be done is by restructuring the package to grouping some similar functionalities, like for `job` command, it is put in one place like struct and/or package.

**Comment by irainia** [comment]
The following is the approach internally discussed to address this issue. Basically, it is to group the related components into its own structure within a dedicated package.

* main.go

```go
package main

// ...

func main() {
	// ...
	root := cmd.NewRoot()
	if err := root.Execute(); err != nil {
		panic(err)
	}
	// ...
}
```

* cmd/root.go

```go
package cmd

type root struct {
	*cobra.Command
}

func NewRoot() *cobra.Command {
	output := &root{
		Command: &cobra.Command{
			// ...
		},
	}
	jobCommand := job.NewCommand()
	output.AddCommand(jobCommand)
	return output.Command
}
```

* cmd/job/job.go

```go
package cmd

type job struct {
	*cobra.Command
}

func NewCommand() *cobra.Command {
	output := &job{
		// ...
	}
	jobCreateCommand := NewCreateCommand("inside job create")
	output.AddCommand(jobCreateCommand)
	return output.Command
}
```

* cmd/job/job_create.go

```go
package cmd

type jobCreate struct {
	*cobra.Command

	message string
}

func (j *jobCreate) GetMessage() string {
	return fmt.Sprintf("message: %s", j.message)
}

func (j *jobCreate) Execute(cmd *cobra.Command, args []string) error {
	fmt.Println(j.GetMessage())
	return nil
}

func NewCreateCommand(msg string) *cobra.Command {
	output := &jobCreate{
		// ...
	}
	output.message = msg
	output.RunE = output.Execute
	return output.Command
}
```

**Comment by irainia** [comment]
> The following is the approach internally discussed to address this issue. Basically, it is to group the related components into its own structure within a dedicated package.
> 
> * main.go
> 
> ```go
> package main
> 
> // ...
> 
> func main() {
> 	// ...
> 	root := cmd.NewRoot()
> 	if err := root.Execute(); err != nil {
> 		panic(err)
> 	}
> 	// ...
> }
> ```
> 
> * cmd/root.go
> 
> ```go
> package cmd
> 
> func NewRoot() *cobra.Command {
> 	output := &cobra.Command{
> 		Use:   "playground",
> 		Short: "commands that handle command",
> 	}
> 	jobCommand := job.NewCommand()
> 	output.AddCommand(jobCommand)
> 	return output
> }
> ```
> 
> * cmd/job/job.go
> 
> ```go
> package cmd
> 
> func NewCommand() *cobra.Command {
> 	output := &cobra.Command{
> 		Use:   "job",
> 		Short: "command to handle job operation",
> 	}
> 	jobCreateCommand := NewCreateCommand("inside job create")
> 	output.AddCommand(jobCreateCommand)
> 	return output
> }
> ```
> 
> * cmd/job/job_create.go
> 
> ```go
> package cmd
> 
> type jobCreate struct {
> 	message string
> }
> 
> func (j *jobCreate) GetMessage() string {
> 	return fmt.Sprintf("message: %s", j.message)
> }
> 
> func (j *jobCreate) RunE(cmd *cobra.Command, args []string) error {
> 	fmt.Println(j.GetMessage())
> 	return nil
> }
> 
> func NewCreateCommand(msg string) *cobra.Command {
> 	jobCreate := &jobCreate{
> 		message: msg,
> 	}
> 	output := &cobra.Command{
> 		Use:   "create",
> 		Short: "command to create a job",
> 	}
> 	output.RunE = jobCreate.RunE
> 	return output
> }
> ```

updated the approach, from previously embedding the cobra command to currently not. this is to avoid confusion and to separate responsibility when more methods are to be added. as of writing, put some update in the mentioning draft PR.

**Comment by irainia** [comment]
> The following is the approach internally discussed to address this issue. Basically, it is to group the related components into its own structure within a dedicated package.
> 
> * main.go
> 
> ```go
> package main
> 
> // ...
> 
> func main() {
> 	// ...
> 	root := cmd.NewRoot()
> 	if err := root.Execute(); err != nil {
> 		panic(err)
> 	}
> 	// ...
> }
> ```
> 
> * cmd/root.go
> 
> ```go
> package cmd
> 
> func NewRoot() *cobra.Command {
> 	output := &cobra.Command{
> 		Use:   "playground",
> 		Short: "commands that handle command",
> 	}
> 	jobCommand := job.NewCommand()
> 	output.AddCommand(jobCommand)
> 	return output
> }
> ```
> 
> * cmd/job/job.go
> 
> ```go
> package cmd
> 
> func NewCommand() *cobra.Command {
> 	output := &cobra.Command{
> 		Use:   "job",
> 		Short: "command to handle job operation",
> 	}
> 	jobCreateCommand := NewCreateCommand("inside job create")
> 	output.AddCommand(jobCreateCommand)
> 	return output
> }
> ```
> 
> * cmd/job/job_create.go
> 
> ```go
> package cmd
> 
> type jobCreate struct {
> 	message string
> }
> 
> func (j *jobCreate) GetMessage() string {
> 	return fmt.Sprintf("message: %s", j.message)
> }
> 
> func (j *jobCreate) RunE(cmd *cobra.Command, args []string) error {
> 	fmt.Println(j.GetMessage())
> 	return nil
> }
> 
> func NewCreateCommand(msg string) *cobra.Command {
> 	jobCreate := &jobCreate{
> 		message: msg,
> 	}
> 	output := &cobra.Command{
> 		Use:   "create",
> 		Short: "command to create a job",
> 	}
> 	output.RunE = jobCreate.RunE
> 	return output
> }
> ```

updated the approach, from previously embedding the cobra command to currently not. this is to avoid confusion and to separate responsibility when more methods are to be added. as of writing, put some update in the mentioning draft PR. cc: @sravankorumilli

**Comment by ravisuhag** [comment]
I mean directly using the RunE of cobra command. Check this for example. 
https://github.com/odpf/guardian/blob/main/cmd/appeal.go
What is our need to collect a message in command constructor and having a dedicated jobCreate struct?

**Comment by irainia** [comment]
> I mean directly using the RunE of cobra command. Check this for example. https://github.com/odpf/guardian/blob/main/cmd/appeal.go What is our need to collect a message in command constructor and having a dedicated jobCreate struct?

Based on this example, it's similar to the current approach being used by Optimus. In the current Optimus, there are a lot of functions, vars, and constants within one package. Sometime it's not easy to read without better segregation between one command and another. This update is to group some similar functionalities. The grouping is in two levels, the structure level and the package level.

* the struct level allows us group some highly related functionalities into one. take an example of `job` and `job_create` command. some functions are only specific for job create not job, and vice versa. if these job and job create are to be in the same package, then some functions will be cluttered again. and during developement, sometime IDE (depending on which IDE being used) will provide some unnecessary suggestions.
* for the package level, sometime in a package we want some "public" values that will be used by some commands, but not available to the outside. for example, some `regex` expression meant for surveys, but not for actual job commands. similar with the struct level, this helps to reduce verbosity during developement.

**Comment by irainia** [comment]
There are two concerns (so far) that will be addressed when we are using struct:

* parameter functions

With grouping by struct, we can reduce the number of parameter being passed to one or more functions (or methods). If we check the current implementation, there are some functions that accepts many arguments, such as the one for `deploy` command. With the struct, we can just put any state into the struct and access it when it's needed. If we do not send it as argument, another way is to make a "public" variable within package. But, adding more of these variables being accessible within the package is not recommended.

* naming functions

With the struct, we can just focus the grouping with the struct name. If we only use functions, then in order to add more context, we will need to use a longer name.

If we don't use struct, we have to deal with longer naming functions with more parameters on it.

**Comment by ravisuhag** [comment]
@irainia Can you give more concrete example of this?

**Comment by irainia** [comment]
> @irainia Can you give more concrete example of this?

Sure, one example that we can observe can be found [here](https://github.com/odpf/optimus/blob/429b8c89bcea4ee00a8803e624f852de2a3c944d/cmd/deploy.go#L101). And if we look further back, another example can be checked [here](https://github.com/odpf/optimus/blob/22696aae1f82161c5d25605a541b1e7efb45b0d7/cmd/deploy.go#L79).

**Comment by irainia** [comment]
> What I feel is it was fine as it was before, it's just people have low tolerance of these things now working with languages like `java` and gets easily annoyed/confused. There are three kinds of scoping we can observe here overall
> ...

This issue is not only about "function to get the related command" like `jobCreateCommand`, but it's also about all functions required to accomplish the instruction in those command. For example, when we try to deploy a job, there are some functions being called. Like, if we check the current implementation, we need to call function to deploy job only, then resource, and some other function in between. Surely we can combine them into one big function. But, putting all those things in one function makes it hard to maintain it.
