### ISSUE TITLE
Provide Basic Job Monitoring and SLA Dashboard

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#345]
Metrics : Task Delay, Task Duration, Job Duration, Status and SLA Miss Time Delta

Scope 
1. capturing metrics at job run attempt level.
2. handle SLA miss events. 
3. build the dashboard.

**Comment by Mryashbhardwaj** [comment]
PR: https://github.com/odpf/optimus/pull/395

**Comment by ravisuhag** [comment]
@Mryashbhardwaj Linked issues are still open. Can they be closed now?
