### ISSUE TITLE
Optimus Sensor with automated inference.

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#359]
**Describe the solution you'd like**
An Optimus sensor should check given a resource and the start and end dates, will check the corresponding jobs are successful or not. If Optimus Sensor is used in the Optimus setup then it should be automatically inferred.

**Users** 
1. Other Optimus Users with in the same organization managing a different 
2. Users using a different system other than optimus for managing the pipelines

**Describe alternatives you've considered**
Relying on respective storage sensors with automated inference, but it has its own challenges around data completeness and data quality.

- [x]  #398
- [x] #399
- [x] #400

**Comment by SumitAgrawal03071989** [comment]
Hello @sravankorumilli, mentioned optimus sensor should be different from http sensor? So both http sensor and optimus sensors will co-exists for different use cases?

**Comment by arinda-arif** [comment]
Approach of using HTTPSensor but with automated inference (TBD):

Given there are 2 Optimus deployments, Optimus A and Optimus B.

There is a bq2bq job in Project A that is registered in Optimus A with below query:
```sql
Select 
sample_field_project_a, 
sample_field_project_b 
from `project-a.playground.sample` 
left join `project-b.playground.sample` on (..)
```

**Dependency Resolution Process**

Dependency resolution result of the job:
- project-a.playground.sample 	 		(registered in Optimus A)
- project-b.playground.sample			(registered in Optimus B)

Optimus will try to fetch the jobs using above resources.
1. First attempt (existing) is to query from Optimus DB using the resource name. It will try to search from the `destination` field in the job table.
    - If this dependency project is equal with the current project, the dependency type is `intra`.
    - If project is different, the dependency type is `inter`.
2. Second attempt (when the job is not found in the current project) is to fetch the jobs from Optimus neighbors. Each Optimus deployment will have list of optimus neighbors registered, and will try to find the jobs through each of the neighbor until able to find the job.
    - Similar with other dependencies, Optimus will attach this dependency information in the job spec, however the type will be `external`.
    - For the job deployment asynchronous (WIP) approach, this will also being stored in the job_dependency table.

`project-b.playground.sample` job will not be found in the current project thus will go through the second attempt.


**Compilation Process**
Job dependency with external type will use HTTPSensor. The endpoint will be fetched from the Optimus deployment configuration.

**Comment by sravankorumilli** [comment]
We should update the table such that we can store any sensor details not just limiting to job sensors.
The current sensor that will be inferred will hit an api exposed by another optimus which takes resource urn, dstart and dend so the caller didn't need to know the job or upstream schedule.

**Comment by sravankorumilli** [comment]
We can break the story into two to make the changes on the api and on the sensor aspects.

**Comment by arinda-arif** [comment]
Created 3 issues for this:
1. [Persist Job Sources and Utilize for Job Compilation](https://github.com/odpf/optimus/issues/398)
2. [Provide APIs to get JobSpec and JobRuns based on Resource URN](https://github.com/odpf/optimus/issues/399)
3. [Support Optimus Sensor](https://github.com/odpf/optimus/issues/400)
