### ISSUE TITLE
Improve Logging and Client Communication in case of Failures

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#366]
**Is your feature request related to a problem? Please describe.**
The better the logging the better we understand what is happening in the system. That improves efficiency of the developers and admins. 

**Describe the solution you'd like**
As part of this epic one round of going through the entire code flow and correcting the log levels and remove any unnecessary logging and improve the client contracts especially during failure scenarios.

**Comment by irainia** [comment]
Previously had a thought about this. One approach we can consider is adding **id** on our log, more specifically on server log. As Optimus sometimes handles a lot of request at a short amount of time, it will not be easy to find which flow we should follow to trace any possible bugs. With the help of request **id**, this could help us to trace it faster. The concept is similar to how we currently handle deployiment, using id. But, this is specific for log only. The flow is like the following:

* client create a request, such as creating a resource
* in here, we can either let the client generate the id or the server handle it if not being provided
* when server accepts the request, it will write each process using log
* and during wiring the log, the **id** previously mentioned should be included in that log

Let's say there is an error during the process. The server just needs to send a high-level error to the client, along with the log **id** in case they want to understand more detail. We can accept a user ticket to let the developer check the log based on the log **id** the user send to them. Or, we can provided an endpoint or API to allow the user to view the error by themselves based on the **id** provided by the user.
