### ISSUE TITLE
Provide Charts for Deploying Optimus on Kube

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#369]
- Optimus Server
- Service & Ingress
- Monitoring Side Car

**Comment by ravisuhag** [comment]
@sravankorumilli This should be added in the charts repo.

**Comment by sravankorumilli** [comment]
Yes will be added there

**Comment by sbchaos** [comment]
Opened a pr on charts repository: https://github.com/odpf/charts/pull/63

After the pr is merged we will use it to test the deployment.
