### ISSUE TITLE
Provide APIs to get JobSpec and JobRuns based on Resource URN

### ISSUE THREAD

**Issue by arinda-arif** [odpf/optimus#399]
1. Provide API to fetch `JobSpec` based on resource URN. This will be used on Optimus Sensor creation, to identify whether the particular resource needs a cross Optimus sensor or can be ignored.
```(GET) {optimus_host}/api/v1beta1/jobs```
    _Params: resource_destination_
2. Provide API to fetch `JobRuns` based on resource URN. This will be used by the Optimus Sensor to check the run status of the particular resource given the date range.
    ```(GET) {optimus_host}/api/v1beta1/jobruns```
    _Params: resource_destination, dstart, dend_
    Response:
    ```json
     {
        "success" : true,		
        "job_runs" : [
            {
                "scheduled_at" : "2022-01-01 02:00:00",
                "state" : "failed"
            }
        ],
        "message" : ""
    }
    ```

**Comment by SumitAgrawal03071989** [comment]
[PR](https://github.com/odpf/optimus/pull/406) for this issue

**Comment by sravankorumilli** [comment]
{optimus_host}/api/v1beta1/jobruns this api doesn't need to be updated.
