### ISSUE TITLE
Add Guide for Development Setup

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#418]
### Background

If we look at the current documentation, like README.md (latest commit [here](79fdefa1012caed723dd681e3e02eff79830f9e7)) or the [blog documentation](https://odpf.github.io/optimus/docs/introduction), there is no guide being provided to setup local for development. A little example, what needs to be prepared in the local environment to do test (unit test and integration test)? Another, what database and which version should we prepare? If no guide or the guide is not clear to set up for local testing, then little chance any developers will use it to test locally. And this could hinder adoption.

### Proposal

We need to have a comprehensive guide and documentation for both developer and the general user. The guide and documentation should include as many details as possible, no matter how small they are. Be it the database and its version, or the scheduler like Airflow, or even what environment variable is needed, how to deploy, how to set up the job, what to prepare for resources, how to monitor the whole system, and more. Everything should be included.

**Comment by irainia** [comment]
Additional considerations that need to be included. We also need to put a glossary for every keyword we use. Another thing to add is a step-by-step guide for each possible activity. For example, in order to deploy job, what to prepare and what to do, and with recommendation and exception would be great, such as how to write project configuration for the deployment.

**Comment by sravankorumilli** [comment]
Should be handled as part of #168
