### ISSUE TITLE
optimus playground to play around with windowing configurations

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#429]
users should be provided with an optimus playground command
through which users are guided interactively to know more about some key areas in optimus.
1. windowing
2. render

As part of this story user should be provided an option to experiment with windowing.
User should be provided with questions through which optimus takes all inputs needed to compute the dstart & dend.
Inputs needed 

1. window_size
2. window_offset
3. window_truncate : `d`, 'm`, 'w`
4. schedule_date : 24th 2:AM 
`dstart` `dend`

The output is window_start & window_end.

**Comment by irainia** [comment]
closing this as it's already implemented
