### ISSUE TITLE
Refactor cmd package to separate command implementations and its utilities

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#441]
### Background

This issue is highly impacted by #336 and its PR #431. Based on these, there's a new package being introduced, which is named `internal`. After a discussion, there are three basic components under `cmd` package:

1. sub-command registration
1. sub-command implementation
1. some functions that support the sub-command

The current `cmd` separated the first and second point. The third point is also separated properly. However, if we look a bit deeper, the changes after the mentioned PR contains sub-packages like the following:

```
|-- cmd/
|    |-- admin/
|    |-- backup/
|    ...
|    |-- internal/
|    |-- server/
|    |-- survey/
|    |-- command.go
```

`command.go` file mostly contains initialization and registration of sub-command. Each sub-command implementation is defined under its own package. Like `admin` sub-command under package `admin`. However, some of these packages are not the direct implementation of a sub-command, like `server` or `survey` or even `internal`. We can't really use `command.go` file as it will introduce cyclic dependency. With this, we can consider it as less consistent.

To be more consistent, this issue proposes two options:
* reorganize the cmd implementations so there won't be any package that are not direct implementation of the sub-command, or
* put everything that are not the direct implementation of sub-command under `internal` package.

#### First Option

If we go through the first option, we can have only packages with the direct implementation of the sub-package. However, we have to put in mind that some similar functionalities could occur because one or more sub-command implementations are similar. For example, the use of package `survey` is to solve this issue, where all other implementations under `cmd` can refer to this package if survey is required.

#### Second Option

If we go through the second option, we can contain all packages that are not directly related to the sub-command in a single place. This reduces the chance of duplications. However, even though the `internal` package is a bit special, we have to be careful on the implementations because if this package gets bigger, then it could be similar to `utils` package. Even though a bit excessive, this can be reduced by using sub-command if possible.

**Comment by sravankorumilli** [comment]
this is already addressed in the above issues mentioned

**Comment by sravankorumilli** [comment]
Reopening as not everything is addressed
