### ISSUE TITLE
Support Yaml Plugins in Optimus which demand just a simple Command Line Experience

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#464]
**Description**
Optimus should provide a mechanism to load the plugins which are defined in Yaml format.

**Acceptance Criteria**

- [x] The newly added yaml plugins should work at the time of job creation, dependency resolution, deployment & execution.
- [x] If both Yaml based plugin and server plugin is configured then server plugin takes the priority
- [ ] Implement Survey that is simplifies and uses YamlPlugins

**Comment by smarch-int** [comment]
@sravankorumilli Re-implementing survey to simplify can be converted to issue.
