### ISSUE TITLE
Feat : Optimus to provide a mechanism for users to verify the jobs

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#468]
**Is your feature request related to a problem? Please describe.**
Currently optimus render tried to address this but it is not complete and proper, as it works only for the jobs which are in local directory. It doesn't provide the sensors that will be created. Given a job schedule time it should show what all upstreams the jobs will depend on.

**Describe the solution you'd like**
Should expect a command and api which can work to provide the details which can be later extended to do a dry run.

**Describe alternatives you've considered**

**Additional context**

**Comment by sbchaos** [comment]
This is addressed as part of `job inspect`
