### ISSUE TITLE
Airflow depends on past configuration should be applied to transformation task only

### ISSUE THREAD

**Issue by arinda-arif** [odpf/optimus#487]
Currently, the depends-on-past configuration value is being applied in the whole dag. This means the sensors that are created is having the value based on what user's inputted, even though the sensors are auto-generated by Optimus. This causes a problem if there is a new sensor created for a particular job, making the users have to mark the previous date sensor as complete. 

The user-defined depends-on-past value should only be applied to the transformation task.

**Comment by ravisuhag** [comment]
@arinda-arif Can you please mention the reason to close this?

**Comment by arinda-arif** [comment]
This issue is closed as this has been fixed by [this change](https://github.com/odpf/optimus/pull/488), where the user-defined `depends on past` config is only applied to the transformation task.
