### ISSUE TITLE
Preserve history of Airflow sensor task by having the same sensor name as internal sensor task

### ISSUE THREAD

**Issue by arinda-arif** [odpf/optimus#490]
There are 2 kinds of Optimus sensor: internal and external optimus sensor. Currently, internal sensor uses the job name as the sensor ID, while external sensor uses host, project, and the job name.

This might causes an issue when a job moved from 1 server to another server, where the history of the sensor will not be preserved as the task ID has changed.

**Comment by sravankorumilli** [comment]
this is already done
