### ISSUE TITLE
chore: remove `RegisterInstance` API

### ISSUE THREAD

**Issue by Mryashbhardwaj** [odpf/optimus#506]
**Description**
remove the `RegisterInstance` API , and rely completely on `jobRunInput`

**Acceptance Criteria**

- [x] There should not be any log of `jobRunInput` API failures , in past 1 month , for us to be able to realise this cleanup.
- [ ] remove  `instance` and `job_run_old` tables from database

**Comment by deryrahman** [comment]
Is it duplicate? Seems like quite similar with [this issue](https://github.com/odpf/optimus/issues/443)
