### ISSUE TITLE
Create job management bounded context

### ISSUE THREAD

**Issue by sbchaos** [odpf/optimus#575]
**Description**
Core job management is not properly encapsulated and can be accessed and modified everywhere. We need to encapsulate the dependency resolution and other pieces to only be accessible by proper interfaces. Need to add domain module to handle the core job management bounded context. 

Depends on : [574](https://github.com/odpf/optimus/issues/574)

**Acceptance Criteria**

- [x] Core Job management should be encapsulated
- [x] Client should still rely on the same apis & there shouldn't be any change in the api contract. 
- [x] Job dependency should be resolved & persisted for all including external which will improve the performance and as well as it is something that shouldn't happen during the deployment.
- [x] Dependency Resolution shouldn't happen in any other apis other than the deploy,update,add, and it should be part of job BC only.
- [x] Should address issue on dependency resolution as mentioned in [504](https://github.com/odpf/optimus/issues/504). 
- [x] Users should have a clear visibility around the status of the jobs whether is validated, dependency resolved, deployed.
- [x] Relevant metrics and logging should be improved to address the debuggability concerns as of today.
- [x] Create a CRUD interface for the jobs, currently we have only upsert.

**Scope**
- [ ] Introduction of the new job bounded context with all the handlers & services.
- [x] AddJobSpecification
- [x] UpdateJobSpecification
- [x] DeleteJobSpecification
- [x] GetJobSpecification
- [x] ListJobSpecification - need to check the need for this api.
- [x] InspectJobSpecification
- [x] ReplaceAllJobSpecification
- [x] RefreshJobSpecification
- [x] ValidateJobSpecification
- [x] GetJobTask
- [x] GetWindow
- [ ] Introduction of new resource manager (for external dependency) to work with the new models being introduced as part of this BC.
- [ ] Introduction of new repositories to work with the new models being introduced as part of this BC.
- [ ] Improve the debuggability through logging, capturing the right metrics & updating the dashboards.
- [ ] Get job specification with upstream (in service) as needed by Scheduling Bounded Context

**Out of Scope**

1. Moving all the code related to job scheduling to separate domain
2. Compilation engine and plugin repository
3. Window models will be reused.

**Comment by arinda-arif** [comment]
**AddJobSpecifications Scenarios**

- should be able to add multiple jobs. if some of the jobs are failed, the rest of the jobs should still be added
- users should know what all jobs have issues
    - job spec invalid issue
    - job already exist issue
    - sensor not created issue
    - unable to connect to external optimus issue
    - plugin issue
    - db insertion issue
- if a job has invalid static dependency, the job will still be persisted and deployed.
    - invalid dependency is when job is not found
- if a job has unresolved inferred dependency, we will not inform the users. However, we are storing it in db.
- dependency resolution will be done only for the job in the request and all the existing jobs will be untouched.
    - solution is to schedule a job refresh.
- all dependencies will be stored in a table, including the unresolved ones -> job_upstream table
    - for static, the project name (if exist) and job name will be stored and marked as 'unresolved'
    - for inferred, the resource URN will be stored and marked as 'unresolved'
    - for ignored, the resource URN will be stored and marked as 'ignored'
        - plugin needs to be updated
    - for the rest, we will marked as 'resolved'
- there should be job monitoring page. it will be in a job level information
    - able to show any dependency info and issues. includes the jobs that are not passed the validation.
    - later can also show job run info, SLA
- should capture the overall journey of AddJobSpecifications request
    - tracing
    - logs
    - high level in prometheus
        - number of jobs in a request, number of failed in dependency resolution, etc -> prometheus metrics
- AddJobSpecifications, Update, others & ReplaceAll (any API) will not returning the deployment ID
    - Deployment will be triggered from the scheduling BC API
- when adding a job which is soft deleted earlier, then:
    - If it is in the same namespace, recreation is allowed (only update). This job will has the same history.
    - If it is in the different namespace, recreation is not allowed. Should inform that job already exist in other namespace but marked as deleted.


**Out of scope:**
- changing the bq2bq plugin to return the ignored sources and also store the ignored sources in the job_dependencies table
- defining ignored sources in the job spec
- storing job deployment state

**Comment by arinda-arif** [comment]
**DeleteJobSpecifications Scenarios**

- By default a delete is a soft delete, which doesn't cleanup job/task/hook run history from Optimus DB. Marking it as deleted.
- An option for force deleting needs to be provided which removes the entire history from Optimus DB using --clean or --delete-history
- When the job is deleted and it has downstream jobs, user should be notified and deletion should be avoided.
- When the job is deleted and it has downstream jobs, user can still delete it using --force option.
    - Records in job_upstream table will be deleted. This will clear the sensor of the deleted job.

Out of scope:
- Option for force delete which removes the history from the scheduler DB as well.
- When the job is deleted with force option, all downstream jobs owners will be notified.
- A delete should check if there are any external jobs depending on the current job -- low priority
