### ISSUE TITLE
Enrich the `render` command

### ISSUE THREAD

**Issue by Mryashbhardwaj** [odpf/optimus#577]
**Description**
Add details of the issue or feature, relevant RFC or discussion thread.

**Acceptance Criteria**
- [ ] download assets for local as well as a job which is already in the server. (specify using a flag in command)
- [ ] default schedule time is next schedule time of the job and it should be logged explicitly in the client side.
- [x] cleanup of the dump assets functionality and use the server side endpoint.
- [x] this should skip over the secrets, they should not be sent over the wire

Depends on : https://github.com/odpf/optimus/issues/492

**Comment by sbchaos** [comment]
Replaced `render` command with `job inspect`
