### ISSUE TITLE
Introduce Scheduling bounded context

### ISSUE THREAD

**Issue by sbchaos** [odpf/optimus#583]
**Description**
Core scheduler management is not properly encapsulated and can be accessed and modified everywhere. We need to encapsulate the scheduling functions to only be accessible by proper interfaces. As part of this we will introduce a domain for dealing with core scheduling bounded context.

Depends on : [575](https://github.com/odpf/optimus/issues/575)

**Acceptance Criteria**

- [x] core scheduling related logic should be encapsulated
- [x] Client should still rely on the same apis & there should be minimal change in the api contract. 
- [x] All service and handlers related to job runs will be part of this domain
- [x] Remove the old api from Protos.
- [x] Dag compilation should happen properly.
- [x] Dag uploading/updating and deletion of Dags for removed jobs should happen properly. 
- [x] Priority resolution logic should not be changed.
- [x] DAG deploying to Scheduler should be run independently of job spec creation, and dependency and priority resolution 
- [x] Alerting should be proper for SLA misses and Job Failures(only complete DAG failures/not operator failures)
- [x] Relevant metrics and logging should be improved to address the debuggability concerns.
- [x] Re assess the metric collection callbacks/events from the scheduler.
- [x] Re assess the Data Base model for metrics collected for job_run and its breakup(sensors/tasks/hooks).

**Scope**
- [x] Introduction of the new scheduler bounded context with all the handlers & services.
- [x] JobRunInput
- [x] UploadToScheduler
- [x] RegisterJobEvent [takes care of job state updation( scheduling metrics )  and alerting ]
- [x] JobRun
- [x] Introduction of new repositories to work with the new models being introduced as part of this BC.
- [x] Improve the debuggability through logging, capturing the right metrics.

**Out of Scope**
1. Handling of replay functionality in Optimus
2. Handling of backup 
3. GetJobTask API
4. GetWindow API
5. JobStatus API
6. RunJob API

**Comment by Mryashbhardwaj** [comment]
**JobRunInput Scenarios**

- should be able to get job resources such as job assets / evn variables / secrets
- if a job_run exists then fetch execution time from the existing job run.
    - else use schedule time as execution time.

**Out of scope:**
-

**Comment by Mryashbhardwaj** [comment]
**RegisterJobEvent**
- should update job run state appropriately 
  - job run
    - details captured 
      - [refenrece information] -> job name , project name , namespace name 
      - [run state] -> status 
      - [time metrics] -> scheduled time , start time , end time , sla definition 
    - events observed / Callback Mappings
      - `TYPE_JOB_SUCCESS` <- job_success_event  
      - `TYPE_JOB_FAIL` <- job_failure_event
    - Scenarios 
      - creation
        - Entry in job run table is done when a `job_run of given schedule time` is fetched for the first time. The end time here is saved as a long time in future in year 3000.
        - Only one job_run entry remains per job for a given schedule time.
      - updation 
        - on `TYPE_JOB_SUCCESS`, `TYPE_JOB_FAIL` the job state and end_time is updated appropriately, based on information fetched from event.
  - operator run 
    - Note: (sensor_run/task_run/hook_run) is refered as operator_run for brevity.
    - details captured 
      - [refenrece information] -> job run id, operator name
      - [run state] -> status 
      - [time metrics] -> start time , end time
    - events observed / Callback Mappings
      - `TYPE_<operator-type>_START` <-  operator_start_event
      - `TYPE_<operator-type>_SUCCESS` <-  operator_success_event
      - `TYPE_<operator-type>_RETRY` <-  operator_retry_event
      - `TYPE_<operator-type>_FAIL` <-  operator_failure_event
    - Scenarios 
      - creation
        - Entry in (sensor_run/task_run/hook_run) table is done when a `TYPE_<operator-type>_START` event is received. The end time here is saved as a long time in future in year 3000.
        - multiple operator_run entry are persisted based on attemps of that operator
      - updation 
        - on `TYPE_<operator-type>_SUCCESS` ,`TYPE_<operator-type>_RETRY`, `TYPE_<operator-type>_FAIL` the job run state and end_time is updated appropriately, based on information fetched from event. Also if operator_run entry does not already exist, then it is created before running the updation.

- relay alert events to appropriate channels as configured
  - `SLA_MISS`
    - `TODO`:`EVENT FIRING LOGIC STILL NEEDS TO BE ANALYSED` 
    - appropriate msgs are prepared for the configured chanels and a Notification is queued to be sent
  - `TYPE_JOB_FAIL`
    - appropriate msgs are prepared for the configured chanels and a Notification is queued to be sent


**Out of scope:**
- Using the job run information for powering the sensor logic

**Comment by Mryashbhardwaj** [comment]
**JobRun Scenarios**

- should fetch job runs based on the request to power sensor logic.
- Validate the incomming request 
  - if request is invalid, respond with non 200 status code.
- if job runs are not found for the given criteria
  - Then give emtpy response with a 200 status code.
- Run Fetch logic
  - Calculate a set of expected runs based on the request window and the job's cron schedule
    - keeping the status of all as `pending`
  - Fetch runs information from the scheduler
    - this shall have the actual status of the runs
  - Merge the above 2 set of runs
  - Return the so obtained set of runs with the appropriate statuses

**Out of scope:**
- powering this using the metrics captured in job_run table

**Comment by Mryashbhardwaj** [comment]
**UploadToScheduler Scenarios**

- should fetch all jobs in a given project 
  - resolve priorities 
  - group jobs by tenant 
  - compile and upload dags
    - dags are to be uploaded to the scheduler
    - if the namespace folder is empty then delete

**Out of scope:**
- dependency resolution, needs to be done by job bounded context
