### ISSUE TITLE
update Replay, ReplayDryRun and Backup to replace PrepareJobSpecMap

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#589]
**Description**
This is part of [this discussion](https://github.com/odpf/optimus/discussions/479). `PrepareJobSpecMap` is being used by Replay, ReplayDryRun, and Backup to get the lineage of the requested job. This is not necessary, too complex, and inefficient as job sources have persisted.

**Acceptance Criteria**

- [ ] Refactor to Replay, ReplayDryRun, and Backup to replace PrepareJobSpecMap

**Comment by sbchaos** [comment]
Backup has been simplified and does not use this anymore.
