### ISSUE TITLE
Move `CompileAssets` from CommandLineMod interface to DepResMod

### ISSUE THREAD

**Issue by smarch-int** [odpf/optimus#594]
**Description**
CompileAsset method in `CommandLineMod` interface falls out of place and doesn't fit in the interface.
This behaviour is only used in the context of bigquery when the loadmethod is replace ([here](https://github.com/odpf/transformers/blob/main/task/bq2bq/main.go#L274)).
This simplifies the interface for CommandLineMod.

**Acceptance Criteria**

- [ ] CompileAssets should happen as is for `bq2bq`.
- [ ] CLIMod & BaseMod should be removed from the plugin contracts.

**Scope**

- [x] Clean up of CLIMod & BaseMod support from plugin contracts in Optimus.
- [x] Migrating the plugins to move the CompileAssets Functionality to DependencyMod.
- [ ] Remove BasePlugin mod as well as the secret deprecation
- [ ] Adding the binary plugin interface to get the name of the plugin

**Comment by deryrahman** [comment]
@smarch-int  High level changes on those 2 PRs:
- cliMod is renamed to yamlMod, and later on we can say yamlMod as a yaml plugin
- compileAssets is move to dependency resolution, and it's part of depResMod, and later on we can say depResMod as part of binary plugin
- plugin object in the code contains 2 mod interfaces: yamlMod and depResMod. In the case of yaml plugin, the plugin object should have yamlMod, while the case of binary plugin, the plugin object should have yamlMod and depResMod
- basePlugin is deleted, all plugin information belongs to yamlMod
- in the case of binary plugin, binary will be match to their yaml based on the binary filename
- plugin yaml will be loaded first before loading the binary plugin (need to do some enhancement to avoid the mismatch binary plugin that have yaml mod but doesn't have depresmod)
