### ISSUE TITLE
Refactor job service to avoid handling a lot of things

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#600]
**Description**
This issue is part of [this discussion](https://github.com/odpf/optimus/discussions/479). The current (03952e961d54da33aa8daafda45e1d5d3d132d30) job service implementation handles a lot of things, like:

* job spec operation
* job run creation
* job deployment

Maintaining this takes more time than it should.

**Acceptance Criteria**
- [x] job service's responsibility should be thin and clear
- [x] other functionalities outside of the one in the first point is put on their own service

**Tech Details**

The following is one proposal to be considered to address this issue.

- [x] break down job service into multiple service according to its responsibility

**Comment by sbchaos** [comment]
Addressed in redesign.
