### ISSUE TITLE
Zombie job deployment process

### ISSUE THREAD

**Issue by deryrahman** [odpf/optimus#637]
**Describe the bug**
On a certain condition, the job deployment status is still `in progress` while there's no worker assigned to this deployment process. So that it creates the zombie deployment process which this job deployment never be picked up by worker. So every deployment after this issue happen will have a state as a `in queue` forever. It needed to be manually intervene through DB to mark this problematic job deployment status to be `cancelled` / remove it

**To Reproduce**
1. Build optimus by this version https://gist.github.com/deryrahman/984e5254373c365c2c6e989b9095afff
2. Create huge dummy jobs within the project, for example create 5k jobs can use [this script](https://gist.github.com/deryrahman/984e5254373c365c2c6e989b9095afff)
3. Deploy the jobs eg `optimus deploy --namespace-names=ns-5k-jobs --verbose --ignore-resources`
4. Wait until the job deployment status is marked as `in progress`
5. Restart the server
6. Redeploy that jobs or deploy any jobs from any namespace within the project
7. Deployment will stuck forever

**Expected behavior**
Job deployment after the server crash / restarted should be deployed properly. Worker should be able to pick up the new deployment.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by sbchaos** [comment]
We have made the job deployment process sync, so the deployment status is not required anymore.
