### ISSUE TITLE
Improve dev setup enhancing dev experience with proper seeding

### ISSUE THREAD

**Issue by smarch-int** [odpf/optimus#646]
**Description**
Dev setup improvements to  automate the setup/register a project which includes seeding secrets.

**Acceptance Criteria**

**Scope**

- [x] Script to load secrets ```./load_secrets.sh {{ filepath/to/secrets }}```
- [x] Makefile to expose  below params : users don't have to tweak values.yaml (no wrapper helm )
```Port, Dags path, Plugin Paths```
- [x] Add default Echo Plugin - added to optimus repo

**Comment by deryrahman** [comment]
design changes:
- the secret key value will be present in yaml file
- list of plugin artifact also will be present in yaml file instead
- `make _setup.secrets`: run the load secret script and read it from the setup.yaml
- `make _setup.plugins`: run the plugin install script that define in setup.yaml
