### ISSUE TITLE
Add ability to download all jobs/resources in a project

### ISSUE THREAD

**Issue by sbchaos** [odpf/optimus#708]
**Is your feature request related to a problem? Please describe.**
Optimus currently lacks ability to dump all the jobs present in a project, it can be used for inspecting or backing up the specs present in database.
This can also include jobs which are deleted, can be sent back as archived.

**Describe the solution you'd like**
Add command to download all the resources and jobs in a project as yaml files.

**Describe alternatives you've considered**
Currently no other alternative other than taking a dump of database.

**Comment by irainia** [comment]
This analysis is part of releasing redesign. Extracting YAML is required, in order

**Usage**

- Fetch active and soft-deleted jobs
- Fetch resources
- Jobs & Resources to be fetched are being filtered by:
    - All jobs / resources in the server (no filter)
    - Project, or 
    - Project & namespace

**Current Condition**

- For job, Optimus already has GetJobSpecifications API which can be used to fetch the jobs, however it does not support:
    - filter per project & namespace
    - soft deleted jobs
- For resource, Optimus already has ListResourceSpecifications, however
    - ListResourceSpecifications API needs project, namespace, and datastore filters (cannot choose only project).
    - There is no API to list projects or namespaces. If this exist, we can avoid modifying ListResourceSpecifications and have multiple requests per namespaces.

**Command**

optimus job [TBD] [arguments]

optimus resource [TBD] [arguments]

TBD: possible commands are export, extract, download.

Arguments:

- Project Name
    - --project-name
-  Directory
    - --dir
- Include deleted jobs
    - --with-deleted
-  Host
    - --host
- [TBD] Config
    - Might not include this as in config, job&datastore paths are available. Might confuse where to put the downloaded jobs. 
    - --config

**Output Directory Structure**

Example: `--dir=migration`

Output:
```
  - migration/
    |-- project_1/
      |-- namespace_1/
          |-- jobs/
              |-- job_name_1/
                  |-- job.yaml
                  |-- assets/
                      |-- query.sql
                      |-- ...
              |-- job_name_2/
              ...
          |-- resources/
              |-- resources_name_1/
                  |-- resource.yaml
              |-- resources_name_2/
              ...
          |-- archive_jobs
      |-- namespace_2
          ...
    |-- project_2/
    ...
```

cc: @arinda-arif
