### ISSUE TITLE
Dataset Resource Failed in Deployment

### ISSUE THREAD

**Issue by irainia** [odpf/optimus#746]
**Describe the bug**
This bug happens when we try to deploy resource with empty spec, with the current example is with type of BigQuery `dataset`. Normally, when we want to deploy for creation of dataset, we mostly set the spec field to be empty. However, during deployment process, if we set the spec field to be empty, the resource will be counted as breaching the requirements.

**To Reproduce**
1. Create a resource with type of dataset, which normally has empty spec field
2. Do deployment through client
3. Some errors will be presented

**Expected behavior**
There are two kinds of expectations, one that is already clear and another still needs to be discussed.
* for the one that is clear, the expectation is that whenever we send resource for deployment, the set of business requirement need to be fixed. specific example in the case of `dataset`, since normally spec is empty, we should allow it to be empty instead of raising error like the current behavior.
* for the one that still needs to be discussed, we need decide what to do in case there is a failure in one or more resources in a namespace. the current behavior for resource deployment is whenever we encounter one or more errors before service deployment, we skip the deployment for that namespace and continue to the next one.

**Additional context**
* so far, we find this bug only when deploying bigquery dataset

**Comment by sbchaos** [comment]
We are not fixing it for deploy at the moment, users do not need to provide empty spec for dataset, optimus already creates empty dataset.
